name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./

  send_email_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send email notification
      env:
        SMTP_SERVER: smtp.gmail.com
        SMTP_PORT: 587
        SMTP_USERNAME: ${{ secrets.MAIL }}
        SMTP_PASSWORD: ${{ secrets.PASS }}
        EMAIL_TO: gaston.ibarra@avenga.com
      run: |
        echo "Se ha realizado una modificación en el repositorio. Por favor revisa los cambios."  $EMAIL_TO
